// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCPUUsage():Promise<any>;

export function WailsInit(arg1:any):Promise<void>;
